### ISSUE TITLE
Running as non root user crashes the program

### ISSUE THREAD

**Issue by milin** [okoye/HA-OSCAR#13]
gituser@git-server:~/HA-OSCAR/binaries$ python haoscar_wizard.py 
Traceback (most recent call last):
  File "haoscar_wizard.py", line 30, in <module>
    logger.initialize()
  File "../halib/Logger.py", line 36, in initialize
    FILE = open(filename, "w")
IOError: [Errno 13] Permission denied: '/var/log/haoscar/haoscarlog'

**Comment by okoye** [comment]
Not a bug rather a feature of the program.
