### ISSUE TITLE
Error encountered when dummy username entered while running haoscarwizard

### ISSUE THREAD

**Issue by milin** [okoye/HA-OSCAR#14]
Enter the IP or DNS hostname of remote system: azul.hpci.latech.edu
Admin username on remote host(read warnings for debian systems): msh032
Traceback (most recent call last):
  File "haoscar_wizard.py", line 48, in <module>
    chaif.remoteSetup()
  File "../halib/chaif/Chaif.py", line 60, in remoteSetup
    remote.initialize()
  File "../halib/chaif/RemoteServices.py", line 49, in initialize
    FILE = open(conf_path, "w+")

**Comment by milin** [comment]
after i created a remote.conf file in /usr/share/haoscar , the bug was fixed and the installation process continued
